source 'https://rubygems.org'

ruby '2.1.5'

gem 'rails', '4.1.8'
gem 'pg', '0.17.1'
gem 'jquery-rails', '3.1.2'
gem 'jquery-ui-rails', '5.0.3'
gem 'sass-rails', '4.0.5'
gem 'bootstrap-sass', '3.3.1.0'
gem 'autoprefixer-rails', '4.0.2.1'
gem 'coffee-rails', '4.0.1'
gem 'therubyracer', '0.12.1'
gem 'execjs', '2.2.2'
gem 'settingslogic', '2.0.9'
gem 'kaminari', '0.16.1'
gem 'devise', '3.4.1'
gem 'cancancan', '1.9.2'
gem 'state_machine', '1.2.0'
gem 'paranoia', '2.0.4'
gem 'audited-activerecord', '4.0.0'
gem 'ransack', '1.5.1'
gem 'virtus', '1.0.3'
gem 'jbuilder', '2.2.6'
gem 'active_model_serializers', '0.9.2'
gem 'activerecord-session_store', '0.1.0'
gem 'rails-observers', '0.1.2'
gem 'unicorn', '4.8.3'
gem 'unicorn-worker-killer', '0.4.2'
gem 'capistrano', '3.3.5'
gem 'capistrano-rbenv', '2.0.2'
gem 'capistrano-bundler', '1.1.3'
gem 'capistrano-rails', '1.1.2'
gem 'uglifier', '2.6.0'
gem 'slim-rails', '3.0.0'
gem 'adminlte-rails', '1.3.3'
gem 'enumerize', '0.10.0'
gem 'gon', '5.2.3'
gem 'momentjs-rails', '2.9.0'
gem 'bootstrap3-datetimepicker-rails', '4.7.14'
gem 'underscore-rails', '1.8.2'
gem 'less-rails'
gem 'twitter-bootstrap3-rails'
gem 'active_decorator'
gem 'nested_form'

group :development do
  gem 'rubocop', '0.28.0', require: false
  gem 'pry-rails', '0.3.2'
  gem 'pry', '0.10.1'
  gem 'pry-byebug', '2.0.0'
  gem 'better_errors', '2.0.0'
  gem 'binding_of_caller', '0.7.2'
  gem 'quiet_assets', '1.0.3'
  gem 'bullet', '4.14.0'
  gem 'thin', '1.6.3'
  gem 'hirb', '0.7.3'
  gem 'hirb-unicode', '0.0.5'
  gem 'rails-erd', '1.3.1'
  gem 'rack-mini-profiler'
end

group :development, :test do
  gem 'rspec-rails', '3.1.0'
  gem 'spring', '1.2.0'
  gem 'spring-commands-rspec', '1.0.4'
  gem 'turnip', '1.2.4'
  gem 'factory_girl_rails', '4.5.0'
  gem 'database_rewinder', '0.4.1'
end

group :test do
  gem 'simplecov', '0.9.1'
  gem 'timecop', '0.7.1'
end
